
#ifndef BRIDGEKEEPER_PINOUT_H
#define BRIDGEKEEPER_PINOUT_H


#define MOTOR_ENABLE 6
#define MOTOR_FWD 3
#define MOTOR_BACK 5

#define NAV_L_1_PIN 7
#define NAV_L_2_PIN 9
#define RF_DATA_PIN 8

#define LED1_PIN 12
#define LED2_PIN 13

#endif //BRIDGEKEEPER_PINOUT_H
